import "@/styles/globals.scss";
import Head from "next/head";
import { IdoProvider } from "@/src/context/IdoContext";
import { BootstrapApp } from "@/src/Components/App/BootstrapApp";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Decentral Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IdoProvider>
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />
        <BootstrapApp Component={Component} pageProps={pageProps} />
      </IdoProvider>
    </>
  );
}
