import "@/styles/globals.scss";
import Head from "next/head";
import { IdoProvider } from "@/src/context/IdoContext";
import { BootstrapApp } from "@/src/Components/App/BootstrapApp";
import { QueryClient, QueryClientProvider } from "react-query";

export default function App({ Component, pageProps }) {
  const queryClient = new QueryClient();

  return (
    <>
      <Head>
        <title>Decentral Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <IdoProvider>
          <BootstrapApp Component={Component} pageProps={pageProps} />
        </IdoProvider>
      </QueryClientProvider>
    </>
  );
}
